services:

  mysql:
   image: mysql:8.0
   container_name: mysql-db
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   networks:
    - backend
   ports:
    - "3306:3306" #mysql is running localy on port 3306. to avoid conflict mapped to 3307  here
   volumes:
     - "mysql_data:/var/lib/mysql"
   healthcheck:
       test: ["CMD","mysqladmin","ping","-h","localhost"]
       timeout: 20s
       retries: 10 

  mongodb:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
       - "27017:27017"
    environment: 
     MONGO_INITDB_DATABASE: library_mongo
    networks:
     - backend
 
  app:
   build: .
   container_name: library-management-system
   restart: always
   depends_on:
           mysql:
            condition: service_healthy
   environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
   networks:
     - backend
   ports:
    - "8080:8080"
volumes:
  mysql_data:

networks:
 backend:
  driver: bridge