services:

  #MySQL database
  mysql:
   image: mysql:8.0
   container_name: mysql-db
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   ports:
    - "3306:3306" #mysql is running localy on port 3306. to avoid conflict mapped to 3307  here
   volumes:
     - "mysql_data:/var/lib/mysql"
   healthcheck:
       test: ["CMD","mysqladmin","ping","-h","localhost"]
       timeout: 20s
       retries: 10 
   networks:
      - libnet

  #MongoDB for auditLogs
  mongodb:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
       - "27017:27017"
    volumes:
       - mongo_data:/data/db
    networks:
       - libnet

#Redis
  redis:
    image: redis:6.2
    container_name: redis
    ports:
     - "6379:6379"
    networks:
      - libnet 

#Zookeeper(Kafka dependency)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always
    ports: 
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - libnet

#Kafka broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka 
    restart: always
    ports:
      - "9092:9092"
    depends_on: 
      - zookeeper
    environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
       - libnet

#prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - libnet

#grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - libnet

#config server
  config-server:
    build: 
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
     - "8888:8888"
    networks:
       - libnet


#Spring Boot application
  library-app:
   build: 
     context: ./library-app
     dockerfile: Dockerfile
   container_name: library-management-system
   restart: always
   depends_on:
           mysql:
            condition: service_healthy
           kafka:
            condition: service_started
           mongodb:
            condition: service_started
           redis:
            condition: service_started
           config-server:
            condition: service_started
   environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/library_audit_logs
      SPRING_PROFILES_ACTIVE: dev
   ports:
    - "8080:8080"
   networks:
    - libnet


volumes:
  mysql_data:
  mongo_data:
  grafana-storage:


networks:
  libnet:
   driver: bridge
